### ISSUE TITLE
Index was outside the bounds of the array

### ISSUE THREAD

**Issue by ryanccurtis** [thomasgoldstein/epicedit#18]
When I try to import a ROM, I get an "Unhandled exception" error box.
This is the error:

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at EpicEdit.Rom.Utility.Utilities.BytesToOffset(Byte[] data, Int32 start)
   at EpicEdit.Rom.Utility.Utilities.ReadBlockOffset(Byte[] buffer, Int32 offset, Int32 offsetCount)
   at EpicEdit.Rom.Tracks.Themes.Init(Byte[] romBuffer, Offsets offsets, TextCollection names)
   at EpicEdit.Rom.Game.LoadData()
   at EpicEdit.Rom.Game..ctor(String filePath)
   at EpicEdit.UI.MainForm.OpenRom(String filePath)
   at EpicEdit.UI.Tools.UITools.ImportData(BulkImportDataAction setDataMethod, String[] filePaths)
   at EpicEdit.UI.Tools.UITools.ShowImportDataDialog(BulkImportDataAction setDataMethod, String filter, Int32 maxFileCount)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
Any help would be much appreciated. Thank you!

**Comment by thomasgoldstein** [comment]
Hi. I suppose it is a modified ROM?
Please tell me where to get this ROM / patch, or send it to me privately at stifu at stifu dot fr. Thanks.

**Comment by ryanccurtis** [comment]
Thank you for your reply!
I actually got it figured out myself.
The first ROM was from wowroms, and I think it might have been modified. It had PowerFest 94 in the name. I got the second from romsgames and that worked fine.
